---
title: "Bruce Campell NCSU ST 534 HW 3"
subtitle: "Problems 3.10, 3.18, and 3.21 "
author: "Shumway, Robert H.; Stoffer, David S. Time Series Analysis and Its Applications: With R Examples (Springer Texts in Statistics)"
date: "`r format(Sys.time(), '%d %B, %Y')`"
fontsize: 12pt
header-includes:
   - \usepackage{bbm}
output: pdf_document
---

---
```{r setup, include=FALSE,echo=FALSE}
rm(list = ls())
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(dev = 'pdf')
knitr::opts_chunk$set(cache=TRUE)
knitr::opts_chunk$set(tidy=TRUE)
knitr::opts_chunk$set(prompt=FALSE)
knitr::opts_chunk$set(fig.height=5)
knitr::opts_chunk$set(fig.width=7)
knitr::opts_chunk$set(warning=FALSE)
knitr::opts_chunk$set(message=FALSE)
knitr::opts_knit$set(root.dir = ".")
library(latex2exp)   
library(pander)
library(ggplot2)
library(ggplot2)
library(GGally)
```

## 3.10 cmort analysis - prediction

Let $x_t$ represent the cardiovascular mortality series (cmort) discussed in Chapter 2, Example 2.2. 

### (a) Fit an $AR(2)$ to $x_t$ using linear regression as in Example 3.17. 

### (b) Assuming the fitted model in (a) is the true model, find the forecasts over a four-week horizon, $x^n_{n n+m}$, for $m = 1, 2, 3, 4$ and the corresponding 95% prediction intervals.


## 3.18 cmort analyis - estimation

Fit an AR(2) model to the cardiovascular mortality series (cmort) discussed in Chapter 2, Example 2.2. using linear regression and using Yule- Walker. 

(a) Compare the parameter estimates obtained by the two methods. 

(b) Compare the estimated standard errors of the coefficients obtained by linear regression with their corresponding asymptotic approximations, as given in Property 3.10.

### 3.21 MLE of $ARMA(1,1)$

Generate $10$ realizations of length $n = 200$ each of an $ARMA(1,1)$ process with $\phi = .9$ , $\theta = .5$ and $\sigma^2 = 1$. Find the MLEs of the three parameters in each case and compare the estimators to the true values.

